### ISSUE TITLE
No funciona seleccionar ganador

### ISSUE THREAD

**Issue by jhonvegamas** [arkadev/devtorgame#6]
No realiza acción al presionar el botón en la ventana de torneo #[1063eeb](https://github.com/arkadev/devtorgame/commit/1063eeb07fb906395bb2ca7ae7c250cd66a43311).
![imagen](https://cloud.githubusercontent.com/assets/16909733/24487893/b30169f2-14d8-11e7-9098-2672f42e0542.png)

**Comment by omarsepulveda** [comment]
Se corrige el botón seleccionar ganador [#13f10b9](https://github.com/arkadev/devtorgame/commit/13f10b92e3b5207539471061b088846c82ab25a8)
