### ISSUE TITLE
Optimización de código

### ISSUE THREAD

**Issue by camilobayonag** [arkadev/devtorgame#7]
El archivo Tornament.php en su estructura no cuenta con una apropiada organización. Deberia crearse un archivo .js que contenga todas las funciones [#f7775b8](https://github.com/arkadev/devtorgame/commit/f7775b80b56717ce0462306081d733cb8166843b)

**Comment by omarsepulveda** [comment]
Se crea el archivo tournaments.js para optimizar el código [#13f10b9](https://github.com/arkadev/devtorgame/commit/13f10b92e3b5207539471061b088846c82ab25a8)
